src/WP/ExoBundle/Entity/Image.php
<?php

namespace WP\ExoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile as UploadedFile;


/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="WP\ExoBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;
    private $file;
    private $tempFilename;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }
    /**
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }


    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file) {
        $this->file = $file;

        if(null !== $this->url) {
            $this->tempFilename = $this->url;

            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if(null === $this->file) {
            return;
        }

        $this->url = $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->file) {
            return;
        }

        if(null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if(file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        $this->file->move(
                $this->getUploadRootDir(),
                $this->id.'.'.$this->url
        );
        chmod ($this->getUploadRootDir().'/'.$this->id.'.'.$this->url, 0644);
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload(){
        $this->tempFilename = $this->getUploadRootDir().'.'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        if(file_exists($this->tempFilename)) {
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir() {
        return 'uploads/img';
    }

    public function getUploadRootDir() {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath() {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/WP/ExoBundle/Controller/ExoController.php
<?php

namespace WP\ExoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use WP\ExoBundle\Entity\Asking;
use WP\ExoBundle\Entity\CommentSupply;
use WP\ExoBundle\Entity\CommentAsking;
use WP\ExoBundle\Form\AskingType;
use WP\ExoBundle\Entity\Supply;
use WP\ExoBundle\Form\CommentSupplyType;
use WP\ExoBundle\Form\CommentAskingType;
use WP\ExoBundle\Form\SupplyType;
use WP\ExoBundle\Entity\Contact;
use WP\ExoBundle\Form\ContactType;
use WP\UserBundle\Form\UserType;

class ExoController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $home = $em->getRepository('WPExoBundle:Homepage')->findOneBy([]);
        return $this->render('WPExoBundle:Exo:index.html.twig',array(
            'home' => $home
        ));
    }


    public function askingAction($page)
    {
        $em = $this->getDoctrine()->getManager();

        $nbPerPage = 8;

        $listAsking = $em->getRepository('WPExoBundle:Asking')->getPageAsking($page, $nbPerPage);

        $nbPages = ceil(count($listAsking) / $nbPerPage);

        return $this->render('WPExoBundle:Exo:asking.html.twig', array(
            "listAsking" => $listAsking,
            'nbPages' => $nbPages,
            'page' => $page
        ));
    }

    public function askingAddAction(Request $request)
    {
        $asking = new Asking();

        $form = $this->get('form.factory')->create(AskingType::class, $asking);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $asking->setUser($this->getUser());
            $asking->setIsValidate(0);
            $em->persist($asking);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Demande souscrite.');

            return $this->redirectToRoute('wp_exo_asking');
        }


        return $this->render('WPExoBundle:Exo:askingAdd.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function askingPostAction(Request $request, $id, $page)
    {
        $em = $this->getDoctrine()->getManager();

        $asking = $em->getRepository('WPExoBundle:Asking')->find($id);
        /*$comments = $em->getRepository('WPExoBundle:CommentAsking')->findByAsking($asking,['id'=>'desc']);*/

        $nbPerPage = 8;

        $comments = $em->getRepository('WPExoBundle:CommentAsking')->getPageCommentByAsking($asking->getId(), $page, $nbPerPage);
        $nbPages = ceil(count($comments) / $nbPerPage);
        $comment = new CommentAsking();

        $form = $this->get('form.factory')->create(CommentAskingType::class, $comment);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $user = $this->getUser();
            $comment->setUser($user);

            $comment->setAsking($asking);
            $em->persist($comment);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice2', 'Commentaire ajouté.');

            return $this->redirectToRoute('wp_exo_askingPost', ['id' => $asking->getId()]);
        }
        return $this->render('WPExoBundle:Exo:askingPost.html.twig', array(
            'asking' => $asking,
            'form' => $form->createView(),
            'comments' => $comments,
            'nbPages' => $nbPages,
            'page' => $page
        ));
    }

    public function askingModifAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $asking = $em->getRepository('WPExoBundle:Asking')->find($id);

        $form = $this->get('form.factory')->create(AskingType::class, $asking);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $asking->setUser($this->getUser());
            $em->persist($asking);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Demande modifiée.');

            return $this->redirectToRoute('wp_exo_profile', array(
                "user" => $this->getUser()->getUsername()
            ));
        }


        return $this->render('WPExoBundle:Exo:askingModif.html.twig', array(
            'form' => $form->createView(),
            'asking' => $asking
        ));

    }

    public function askingDelAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $asking = $em->getRepository('WPExoBundle:Asking')->find($id);
        $comments = $em->getRepository('WPExoBundle:CommentAsking')->findByAsking($asking);
        foreach ($comments as $comment) {
            $em->remove($comment);
        }

        $em->remove($asking);
        $em->flush();

        return $this->redirectToRoute('wp_exo_profile', ['user' => $this->getUser()]);

    }


    public function supplyAction($page)
    {
        $em = $this->getDoctrine()->getManager();

        $nbPerPage = 8;

        $listSupply = $em->getRepository('WPExoBundle:Supply')->getPageSupply($page, $nbPerPage);

        $nbPages = ceil(count($listSupply) / $nbPerPage);

        return $this->render('WPExoBundle:Exo:supply.html.twig', array(
            "listSupply" => $listSupply,
            'nbPages' => $nbPages,
            'page' => $page
        ));
    }

    public function supplyAddAction(Request $request)
    {
        if ($this->getUser() == null) {
            return $this->redirectToRoute('fos_user_security_login');
        }


        $supply = new Supply();


        $form = $this->get('form.factory')->create(SupplyType::class, $supply);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $supply->setIsValidate(0);
            $user = $this->getUser();
            $supply->setUser($user);
            $em->persist($supply);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Offre souscrite.');

            return $this->redirectToRoute('wp_exo_supply');

        }


        return $this->render('WPExoBundle:Exo:supplyAdd.html.twig', array(
            'form' => $form->createView()
        ));
    }

    public function supplyPostAction(Request $request, $id, $page)
    {
        $em = $this->getDoctrine()->getManager();

        $supply = $em->getRepository('WPExoBundle:Supply')->find($id);
//        $comments = $em->getRepository('WPExoBundle:CommentSupply')->findBySupply($supply,['id'=>'desc']);


        $nbPerPage = 8;


        $comments = $em->getRepository('WPExoBundle:CommentSupply')->getPageCommentBySupply($supply->getId(), $page, $nbPerPage);
        $nbPages = ceil(count($comments) / $nbPerPage);
        $comment = new CommentSupply();


        $form = $this->get('form.factory')->create(CommentSupplyType::class, $comment);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $user = $this->getUser();
            $comment->setUser($user);

            $comment->setSupply($supply);
            $em->persist($comment);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Commentaire ajouté.');

            return $this->redirectToRoute('wp_exo_supplyPost', ['id' => $supply->getId()]);
        }


        return $this->render('WPExoBundle:Exo:supplyPost.html.twig', array(
            'supply' => $supply,
            'form' => $form->createView(),
            'comments' => $comments,
            'nbPages' => $nbPages,
            'page' => $page
        ));

    }

    public function supplyModifAction(Request $request, $id)
    {

        $em = $this->getDoctrine()->getManager();
        $supply = $em->getRepository('WPExoBundle:Supply')->find($id);

        $form = $this->get('form.factory')->create(SupplyType::class, $supply);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $supply->setUser($this->getUser());
            $em->persist($supply);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'offre modifiée.');

            return $this->redirectToRoute('wp_exo_profile', array(
                "user" => $this->getUser()->getUsername()
            ));


        }
        return $this->render('WPExoBundle:Exo:supplyModif.html.twig', array(
            'form' => $form->createView(),
            'supply' => $supply
        ));
    }


    public function supplyDelAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $supply = $em->getRepository('WPExoBundle:Supply')->find($id);
        $comments = $em->getRepository('WPExoBundle:CommentSupply')->findBySupply($supply);
        foreach ($comments as $comment) {
            $em->remove($comment);
        }

        $em->remove($supply);
        $em->flush();

        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')){
            return $this->redirectToRoute('wp_exo_adminIndex');
        }
        return $this->redirectToRoute('wp_exo_profile', ['user' => $this->getUser()]);

    }


    public function contactAction(Request $request)
    {
        $contact = new Contact();

        $form = $this->get('form.factory')->create(ContactType::class, $contact);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $contact->setIsread(0);

            $em = $this->getDoctrine()->getManager();
            $em->persist($contact);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Message envoyé.');

            return $this->redirectToRoute('wp_exo_contact');
        }
        return $this->render('WPExoBundle:Exo:contact.html.twig', array(
            'form' => $form->createView()
        ));
    }


    public function profileAction($user)

src/WP/ExoBundle/Resources/views/Exo/asking.html.twig
{% extends "WPExoBundle::layout.html.twig" %}
{% block css %}
    <link href="{{ asset("public/css/bootstrap.min.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/modern-business.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/exofex.css") }}" rel="stylesheet">
{% endblock %}
{% block title %}
    Demandes - {{ parent() }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1 class="page-header">Demandes</h1>
                <ol class="breadcrumb">
                    <li><a href="{{ path ("wp_exo_homepage") }}">Home</a>
                    </li>
                    <li class="active">Demandes</li>
                </ol>
            </div>
        </div>
        {% if app.session.flashBag.has('notice') %}
            <div class="row">
                <div class="col-md-6">
                    {% for msg in app.session.flashBag.get('notice') %}
                        {{ msg }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% if app.session.flashBag.has('notice2') %}
            <div class="row">
                <div class="col-md-6">
                    {% for msg in app.session.flashBag.get('notice2') %}
                        {{ msg }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="asking">
            <div class="row">
                <div class="col-md-10">
                    <div class="col-md-4 pull-right">
                        <a href="{{ path('wp_exo_askingAdd') }}">
                            <button type="button" class="btn subscribe btn-success ribbon">Souscrire une demande
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            {% for asking in listAsking %}

                    <div class="row">
                        <div class="col-md-10">
                            <div class="askingBox">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h4>
                                            <strong><a href="{{ path('wp_exo_askingPost',{'id': asking.id}) }}">{{ asking.title }}</a></strong>
                                        </h4>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-2">
                                        <a href="{{ path('wp_exo_profile',{'user': asking.user}) }}" class="thumbnail">
                                            <img src="{{ asset(asking.user.image.webPath) }}" width="260" height="180"
                                                 alt="">
                                        </a>
                                    </div>
                                    <div class="col-md-1"></div>
                                    <div class="col-md-8 descriptionBox">
                                        <p>
                                            {{ asking.description | slice(0,400) }}{% if asking.description | length > 400 %} . . .{% endif %}
                                        </p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-5">
                                        <p>
                                            <i class="icon-user"></i> Publié par <a
                                                    href="{{ path('wp_exo_profile',{'user':asking.user}) }}">{{ asking.user }}</a>
                                            <br/><i class="icon-calendar"></i> le {{ asking.date | date('d/m/Y') }}
                                            {% if asking.isValidate == 0 %}
                                                <br/><i class="icon-comment"></i><a {#class="btn"#}
                                                    href="{{ path('wp_exo_askingPost',{'id': asking.id}) }}">Proposer
                                                une
                                                offre</a>
                                            {% endif %}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

            {% endfor %}
        </div>
        {% if nbPages>1 %}
            <ul class="pagination">
                {% for p in range(1, nbPages) %}
                    <li{% if p == page %} class="active"{% endif %}>
                        <a href="{{ path('wp_exo_asking',{'page':p}) }}">{{ p }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

src/WP/ExoBundle/Resources/views/Exo/askingAdd.html.twig
{% extends "WPExoBundle::layout.html.twig" %}
{% block css %}
    <link href="{{ asset("public/css/bootstrap.min.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/modern-business.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/exofex.css") }}" rel="stylesheet">
{% endblock %}
{% block title %}
    Souscrire une demande - {{ parent() }}
{% endblock %}
{% block content %}
    <div class="container">
        <div id="askingAdd">
            <div class="row">
                <div class="col-md-10 col-xs-12">
                    <h1 class="page-header">Souscrire une demande</h1>
                    <ol class="breadcrumb">
                        <li><a href="{{ path ("wp_exo_homepage") }}">Home</a>
                        </li>
                        <li><a href="{{ path ("wp_exo_asking") }}">Demandes</a>
                        </li>
                        <li class="active">Souscrire une demande</li>
                    </ol>
                </div>
            </div>
            {% form_theme form "bootstrap_3_layout.html.twig" %}
            <!--<div class="col-md-2"></div>-->
            <div class="row">
                <!--<div class="col-md text-center">-->
                <div class="col-md-8 col-xs-12">
                    {{ form(form) }}
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

src/WP/ExoBundle/Resources/views/Exo/askingPost.html.twig
{% extends "WPExoBundle::layout.html.twig" %}
{% block css %}
    <link href="{{ asset("public/css/bootstrap.min.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/modern-business.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/exofex.css") }}" rel="stylesheet">
{% endblock %}
{% block title %}
    Commenter - {{ parent() }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <h1 class="page-header">{{ asking.title }}</h1>
                <ol class="breadcrumb">
                    <li><a href="{{ path ("wp_exo_homepage") }}">Home</a>
                    </li>
                    <li><a href="{{ path ("wp_exo_asking") }}">Demandes</a>
                    </li>
                    <li class="active">{{ asking.title }}</li>
                </ol>
            </div>
        </div>
        <div id="askingPost">
            <div class="row">
                <div class="col-md-10">
                    <div class="askingBox">
                        <div class="row">
                            <div class="col-md-8">
                                {#<p></p>#}
                                <p>
                                    <i class="icon-user"></i> Publié par <a
                                            href="{{ path('wp_exo_profile',{'user':asking.user}) }}">{{ asking.user }}</a>
                                    <br/><i class="icon-calendar"></i>le {{ asking.date | date('d/m/Y') }}
                                    <br/> à {{ asking.date | date('H:i') }}
                                </p>
                            </div>
                            <div class="col-md-4">
                                <div id="ask{{ asking.id }}" class="col-md-1 pull-right {% if asking.isValidate %}isvalid{% endif %}">
                                    <i class="glyphicon glyphicon-ok" ></i>
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <a href="{{ path('wp_exo_profile',{'user': asking.user}) }}" class="thumbnail">
                                    <img src="{{ asset(asking.user.image.webPath) }}" alt="">
                                </a>
                            </div>
                            <div class="col-md-1"></div>
                            <div class="col-md-8 descriptionBox">
                                <p>
                                    {{ asking.description }}
                                </p>
                                <!--<p><a class="btn" href="#">Read more</a></p>-->
                            </div>
                        </div>
                        {% if is_granted('ROLE_USER') %}
                            {% form_theme form "bootstrap_3_layout.html.twig" %}
                            {{ form(form) }}
                        {% endif %}
                        <div class="clear"></div>
                    </div>
                    {% if not is_granted('ROLE_USER') %}

                        <h4><a href="{{ path("fos_user_security_login") }}">inscrivez vous Pour Commenter</a></h4>
                    {% endif %}
                    {% for comment in comments %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="responseBox">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <p>Publié par <a
                                                        href="{{ path("wp_exo_profile",{"user":comment.user}) }}">{{ comment.user }}</a>
                                            </p>
                                            <p>le {{ comment.date | date('d/m/Y') }}<br/>
                                                à {{ comment.date | date('H:i') }}
                                            </p>
                                        </div>
                                        {#</div>#}
                                        {#<div class="row">#}
                                        <div class="col-md-2"></div>
                                        <div class="col-md-10">
                                            <div class="responseBoxText">
                                                <p class="response">{{ comment.comment }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        {% if nbPages >1 %}
            <ul class="pagination">
                {% for p in range(1, nbPages) %}
                    <li{% if p == page %} class="active"{% endif %}>
                        <a href="{{ path('wp_exo_askingPost',{'id':app.request.get('id'),'page':p}) }}">{{ p }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

src/WP/ExoBundle/Resources/views/Exo/index.html.twig
{% extends "WPExoBundle::layout.html.twig" %}
{% block css %}
    <link href="{{ asset("public/css/bootstrap.min.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/modern-business.css") }}" rel="stylesheet">
    <link href="{{ asset ("public/css/exofex.css") }}" rel="stylesheet">
{% endblock %}
{% block title %}
    Accueil - {{ parent() }}
{% endblock %}
{% block content %}
    <!-- Page Content -->
    <div class="container homePageContainer">
        <div id="homePage">
            <!-- Marketing Icons Section -->
            <div class="row">
                <div class="col-md-10">
                    <h1 class="page-header welcome">
                        {{ home.title1 }}
                    </h1>
                    {#<h2 class="secondTitle">#}
                    {#Une solution libre d'échange de compétences#}
                    {#</h2>#}
                </div>

                <div class="col-md-5">
                    <div class="presentBox">
                        <div class="panel">
                            <div class="panelHead">
                                <h4><i class="fa fa-fw fa-check"></i>{{ home.titleArticle1 }}</h4>
                            </div>
                            <div class="panel-body">
                                <p>{{ home.textArticle1 }}</p>
                                <!--<a href="#" class="btn btn-default">Learn More</a>-->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="presentBox">
                        <div class="panel ">
                            <div class="panelHead">
                                <h4><i class="fa fa-fw fa-gift"></i>{{ home.titleArticle2 }}</h4>
                            </div>
                            <div class="panel-body">
                                <p>{{ home.textArticle2 }}</p>
                                <!--<a href="#" class="btn btn-default">Learn More</a>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-10">
                    <div class="well">
                        <div class="row">
                            {#<div class="col-md-10">#}
                            <div class="col-md-8">
                                <p>{{ home.textContactme }}</p>
                            </div>
                            <div class="col-md-4">
                                <a class="btn btn-lg btn-default btn-block" href="{{ path('wp_exo_contact') }}">Contactez
                                    nous</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
            <!-- Portfolio Section -->
            <div class="row">
                <div class="col-md-10">
                    {#<h2 class="page-header">eddsdfsdfsfs</h2>#}
                    {#</div>#}
                    <div class="col-md-6 col-sm-6">
                        <a href="{{ home.linkImg1 }}">
                            <img class="img-responsive img-portfolio img-hover" src="{{ asset(home.img1.webPath) }}"
                                 alt="">
                        </a>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <a href="{{ home.linkImg2 }}">
                            <img class="img-responsive img-portfolio img-hover" src="{{ asset(home.img2.webPath) }}"
                                 alt="">
                        </a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-10">
                    <div class="presentBox">
                        <div class="col-md-6">
                            {#<div class="presentBox">#}
                            <div class="panel">

                                <div class="panel-body">
                                    <p>{{ home.textLogo }}</p>
                                </div>

                            </div>


                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <img class="img-responsive eoe" src="{{ asset(home.logo.webPath) }}" width="360" height="360" alt=" ">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#<hr>#}
{% endblock %}

{#<div class="col-lg-12 col-md-10">#}
    {#<h2 class="page-header">Modern Business Features</h2>#}
{#</div>#}

    {#<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
<!-- Indicators -->
<ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
</ol>

<!-- Wrapper for slides -->
<div class="carousel-inner">
    <div class="item active">
        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
        <div class="carousel-caption">
            <h2>Caption 1</h2>
        </div>
    </div>
    <div class="item">
        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
        <div class="carousel-caption">
            <h2>Caption 2</h2>
        </div>
    </div>
    <div class="item">
        <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
        <div class="carousel-caption">
            <h2>Caption 3</h2>
        </div>
    </div>
</div>


<a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
</a>
</header>#}